### ISSUE TITLE
Failed to resolve: com.toptoche.searchablespinner:searchablespinnerlibrary:1.3.1

### ISSUE THREAD

**Issue by Suraj820** [miteshpithadiya/SearchableSpinner#147]
Failed to resolve: com.toptoche.searchablespinner:searchablespinnerlibrary:1.3.1

**Comment by vjysrgr** [comment]
> Failed to resolve: com.toptoche.searchablespinner:searchablespinnerlibrary:1.3.1

found any solution ??

**Comment by auridgway** [comment]
Seems like the old repo's were taken down for some reason.

Solution I came up with was adding this into my project build.gradle:
`        maven { url 'https://jitpack.io' }
`

Then I reference this repo directly on the master branch rather than old repo services by adding this into the app build.gradle:
`    implementation 'com.github.miteshpithadiya:SearchableSpinner:master'
`

Works for me but I hope this helps

@vjysrgr 
@Suraj820

**Comment by Suraj820** [comment]
@auridgway Thanks for the solution! Adding the Maven URL and referencing the repo on the master branch worked perfectly for me.

**Comment by vjysrgr** [comment]
@auridgway **#ThankYou** for the solution, **Worked** for me too 👍

**Comment by shubhamdoke** [comment]
> implementation 'com.github.miteshpithadiya:SearchableSpinner:master'

Thanks @auridgway for the solution..

**Comment by makunomark** [comment]
Thanks for the solution @auridgway

**Comment by gmshrikant** [comment]
Thanks for the solution @auridgway

**Comment by TechNov** [comment]
Thanks, it work for me
